### ISSUE TITLE
Flexform translations for lables

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakerlist#1]
Please do set up the Flexform with translation handling for the BE.

File: netc_bakerlist/netc_bakerlist/Configuration/FlexForms/Bakerlist.xml

**For example:**

<label>Select storage folder for User </label>

replace it with

<label>LLL:EXT:netcbakerlist/Resources/Private/Language/locallang.xlf:xxx.mytext-item</label>

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Flexform translations for lables
Status > Done
Screenshot > http://www.awesomescreenshot.com/0cc5xpih3f

Regards.
Thank You.
