### ISSUE TITLE
Search results wrong with "Glutenfreies Brot"

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakerlist#10]
If you search for a place like "bern" with the checked "Glutenfreies Brot" and you search for there will be NO resaults at all. Solution for this problem: In the CSV file the import of hte option concerning Glutenfreies Brot" does not work. In the DB there is NO item with this. Seems that it is a bug in the import.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status: Done
Screenshot: http://prntscr.com/bgjrtj , http://prntscr.com/bgjtlc

Regards.
Thank You.
