### ISSUE TITLE
Incorrect SQL database fields

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakerlist#11]
By installing the EXT:netc_bakerlist there is a incorrect mySQL database field in the compare which you can not fix. See printscreen.
![screenshot-2016-06-17-13-21-31](https://cloud.githubusercontent.com/assets/17588253/16149149/eea58568-348e-11e6-857d-ea5a393ba9da.png)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status: Done
Comments: We have changed the Data type of the field and now it's working.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Ok. Works fine. Thanks.
