### ISSUE TITLE
Link on detail page wrong

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakerlist#12]
The www. address on the detail page must be a a href with target _blank and not a link to a email address with a mailto:

![screenshot-2016-06-20-10-40-22](https://cloud.githubusercontent.com/assets/17588253/16187977/9276d7fa-36d3-11e6-9db9-2dd60f27a29b.png)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status: Done
Screenshot: http://prntscr.com/bj0khz , http://prntscr.com/bj1930

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
got it. OK. Works.
