### ISSUE TITLE
Add a checkbox to get preselected search of "Glutenfreie Backery"

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakerlist#13]
Please add a checkbox in the Plug-In to have a preselected choice to have a search with glutenfreie Backery. If the checkbo is selected in the PlugIn there is only the empty search form with the preselected option for Glutenfreie Backery.

![screenshot-2016-06-20-10-44-39](https://cloud.githubusercontent.com/assets/17588253/16188161/72f18d16-36d4-11e6-871a-cff4fa062d97.png)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status: Done
Screenshot: http://prntscr.com/bj1dyf , http://prntscr.com/bj1e2u

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
This one works :)
