### ISSUE TITLE
Search for backery name without Glutenfrei on global backery page gives no results

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakerlist#14]
If you search on the normal backery page without the inital checkd checkbox of "Glutenfreie Bäckerei" and you search for example for the name of "Buchmann" (a backery that has glutenfreies Backery) there is nothing coming.

![backery](https://cloud.githubusercontent.com/assets/17588253/16228215/fc3113bc-37b5-11e6-8619-2bd98546f5be.jpg)

If you search for a backery on the initial checked option of Glutenfreie Backery page with the same name "Buchmann" there is a result.

Info: The option "Glutenfreie Backery" will only tel the user that this backery has specialities also. But it is a fully normal backery that must be showd in the results as well as a normal backery ;-)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status > Done
Screenshot > http://prntscr.com/bqe5zw

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Works. OK. Thanks.
