### ISSUE TITLE
Resources folder inside Resources folder

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_bakerlist#15]
Inside the Resources folder is another Resources folder. 

Can you have a look into that? I think there shouldn't be another Resouces folder inside itself.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

@Resource folder
Status > Done
Comment > Don't know why there were two folders, But now we have uploaded the correct one please check.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Ok.
