### ISSUE TITLE
RealURL configuration

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakerlist#16]
The extension still have no RealURL configuration for the detail pages. Can you fix this?

REALURL configuration for single detail pages as for example like /de/backery-search/details/my-backery-name/

**Comment by jigneshnitsan** [comment]
Hello Angelo

@Correct Real URL
Status > Done

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Where can i have a look to this configuration? If I upload a new CSV the realurl isn't working anymore. Can you please create a Task for the scheduler in the BE to add a "refresher" of the RealURL without installing the EXT:crawler? Thank you very much.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Okay, We will check this and update you by tomorrow on this.

Regards.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

- RealURL issue
Actually it doesn't have any effect from CSV file upload, May be you were facing issues when we were working. So please check it now. And also it doesn't have any issue with EXT:crawler.
Screenshot > http://prntscr.com/bse16j

Regards.

**Comment by angeloprevitali** [comment]
RealURL works. This issue is OK and solved. Thanks.
