### ISSUE TITLE
Single items (details) can not be found in indexed_search

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakerlist#17]
The single items (detail pages) can not be found in indexed_search results.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

We have already tried following things, But yet not any success. 
1. Auto Index search
2. Crawler Extension
3. By setting No cache 

We are trying to resolve this issue, We will inform you soon on this.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Please set up a task for TYPO3 to get indexed with all the item in indexed_search results. This would be the simplest thing without using the EXT:crawler. 
![screenshot-2016-07-11-16-32-14](https://cloud.githubusercontent.com/assets/17588253/16734235/143d145e-4785-11e6-9ca0-cd6a400e7e53.png)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status  > Done
Please check http://prntscr.com/bsenu6, http://prntscr.com/bseo2l, http://prntscr.com/bseojb, http://prntscr.com/bseosi

@Scheduler
We don't need to add this as there is not relation with this. So I guess we need to leave it.

Regards.

**Comment by angeloprevitali** [comment]
After RE-uploading a new CSV file old entried gets NOT deleted in the indexed_search and modified items gets NOT indexed. Please add a TYPO3-Task as described which we can add with a crobjob to get all items indexed correctly.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Regarding indexing single record detail page. We can do it with crawler. which we have done at http://dev.swissbaker.netconsult.ch [Run via backend]

As you said, "we can add with a crobjob to get all items indexed correctly". There is an option for index using cron. For this you have to set cron at server. You can find detail about it at here https://jweiland.net/fileadmin/pdf/vortraege-praesentationen/Handbuch_crawler_Extension.pdf at page no:8 under title "Executing queue with cron-job".

You can get path for "crontab -e" from here http://prntscr.com/bt8owt. For http://dev.swissbaker.netconsult.ch you have this /usr/bin/php /home/httpd/vhosts/netconsult.ch/dev.swissbaker.netconsult.ch/typo3/cli_dispatch.phpsh crawler

Please check this and let us know if it works or not

Regards.

**Comment by angeloprevitali** [comment]
Can you please add a TYPO3-Task as described in https://github.com/NetConsultAG/netc_bakerlist/issues/17#issuecomment-231752265 which we can add with a crobjob to get all items indexed correctly. Thanks. We would NOT use the EXT:crawler installed due to compatibility issues to TYPO3 CMS Version 8.x. Thanks.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

- As you have mentioned here > https://github.com/NetConsultAG/netc_bakerlist/issues/17#issuecomment-231752265 we have R&D on this, But on all help/support we find that we need to use Crawler if we need to achieve this.
- Right now we are checking the extension that you have suggested > https://typo3.org/extensions/repository/view/metaseo 
Still we have not got the exact way that how to implement it, But we are looking into this more.
- If you have any then please suggest a way.
- Just the a point from my end, The reason behind not to use Crawler extension is just the version compatibility, Then as the TYPO3 8.X is still under development and will be available as LTS from next year. So I guess Crawler extension will be compatible upto that.
- Right now we are checking the it how to resolve this issue without using the Crawler extension.

Please let me know if there is anything helpful to us anything from your side.


Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello

you maybe missunderstood me: The EXT:crawler will be compatible for the TYPO3 CMS version 8.x. YES. But a additional configuration for just a thing like that would be very easier if you could add a tsk in the TYPO3 CMS BE.

Have a look to the following file of the EXT:metaseo. It just make nothing else that adding every page into the mySQL DB for get listed for the XML sitemap of Google for example.

So this could be done also for the EXT:netc_bakerlist as well like this.

My solution would be: Adding a task in the BE of TYPO3 that collects all the entries (content) of the bakerlist and add this results with a SQL query into the search results of indexed_search tables.

Step 1: Grab with SQL all entries of the bakerlist with the content
Step 2: Insert them into the mySQL tables of index_fulltext and with the relation to the mySQL table of index_rel.

That's it.

Afterthat every item can be found with indexed_search.

The files i mentioned is located here:
```
D:\Websites\swissbaker.netconsult.ch\typo3conf\ext\metaseo\Classes\Scheduler\Task\SitemapXmlTask.php:
   28  
   29  /**
   30:  * Scheduler Task Sitemap XML
   31   */
   32  class SitemapXmlTask extends AbstractSitemapTask
```

The EXT:metaseo tables that fills the data for the XML sitemap lookes like this: mySQLDB table: tx_metaseo_sitemap

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Thank you for your message and more technical details.

Today we will check your suggested way.

Regards.

**Comment by jigneshnitsan** [comment]
Hi Angelo,

Thank your for your an information. Please take a quick look at below comments:

1. TYPO3 Scheduler:
We know how to create & setup TYPO3 scheduler task. It is easy to generate schedular, Checkout this documentation https://docs.typo3.org/typo3cms/extensions/scheduler/latest/DevelopersGuide/CreatingTasks/Index.html BUT as we know this just initial stage.

2. Metaseo:
You suggested/reference metaseo schedular. But in metaseo they just 're-generate sitemap' from their own XmlGenerator object. We have checked in metaseo it didn't have anything to do with index search, there is nothing to relate with 're-generate index search'.

3. Index search at TYPO3 custom scheduler:
Yes, this is our main task. You said to create custom scheduler with fetch data from EXT:netc_bakerlist and insert in index_fulltext and index_rel tables.

But that's not only things (entry in above two tables) to do for get result in index_search. There is much more complex relation and mechanism index_search follows for store result text, page type, id, path etc. Internally TYPO3 have bit complex & strong process for caching & indexing. We need to process everything which is currently like handling by TYPO3 core or Crawler extension (we have checked that extension - they're doing many things to re-generate indexing). Unfortunately, We have not much knowledge on this stuff :(

Hope you understand what we mean in concern to development, Thank You!

Please share your idea/feedback on the same.

Regards.
Thank You.
