### ISSUE TITLE
BE layout fields "addresse" + "Www Link"

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakerlist#2]
Please just one line of textfield no no textarea. Also with the field Www Link

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

@Please just one line of textfield no no textarea. Also with the field Www Link
Status > Done
Screenshot > http://awesomescreenshot.com/0475xnqv11

Regards.
Thank You.
