### ISSUE TITLE
Location is getting cutted if there were special chars in location field by uploading a csv file

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakerlist#20]
By Uploading a CSV file there is a bug in the field where the location is. I assume it is in the AdressController.php file because the fields of the location gets not converted as the other fields were.

`$csvdata[9]!=''?$records->setAdresse(iconv('windows-1252','utf-8',$csvdata[9])):'';`
`$csvdata[11]!=''?$records->setOrt($csvdata[11]):'';`

Demo file as CSV
[list.zip](https://github.com/NetConsultAG/netc_bakerlist/files/796234/list.zip)

Can you fix this?

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

Thank you for your message.
Okay, Let's check this. We will get back to you soon on this. Regards!

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Please find our update as following.

**Status** > Done
**Screenshots** > 
- CSV address and ORT with special character: http://prntscr.com/ecpf5j
- DB: http://prntscr.com/ecpfhg

**Note:** We have committed our last changes to the Github Repository.

Please also review them at your end. 
Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

looks fine. Thanks.

Regards,
Angelo
