### ISSUE TITLE
Add compatibility to TYPO3 CMS version 7.6 + 8.6 and higher

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakerlist#21]
Hello Jignesh

Can you please adapt the extension for compatibility of TYPO3 CMS versions 7.6 and 8.6 and higher?
You can test it on the actual 8.6.1 DEV plattform of t8.edorf.ch.

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Afternoon!

We have completed the compatibility of the extension with TYPO3 CMS 8.6

**#Backend**
**Extension:** http://prntscr.com/eqlnpv
**Storage:** http://prntscr.com/eqlopw
**CSV Upload:** http://prntscr.com/eqlq3x

**#FrontEnd**
http://prntscr.com/eqlozf , http://prntscr.com/eqlpa2
http://prntscr.com/eqlpf8 , http://prntscr.com/eqlpkm , 

**Note:** We have uploaded all the latest changes to Github, And you can also review this on your staging server: http://t8.edorf.ch/

Please review this from your end and let's know your feedback for the same.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Jignesh

Thanks for your work. There are still two little thing that should be fixed: 

1. The Icon on the left navigation like shown in printscreen should be adapted to the actual TYPO3 CMS version 8.6^. Can you please replace this?

2. The Styling of the Upload-field on the right side isn't Styled like in the usual way. Could you please add the default font for this form?

Thanks for your work and feedback.

Regards,
Angelo

**Comment by angeloprevitali** [comment]
Hello Jignesh

another thing we saw is that the TCS Ables seems not to be fully adapted to the actual V8 version. Can you please fix this, too.?

Thanks.

Reagrds,
Angelo

![screenshot_2](https://cloud.githubusercontent.com/assets/17588253/24598447/ad11d59c-184b-11e7-87a5-ef9861e74642.png)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Thank you for your feedback/reply. 

#Feedback
Okay, Let's check and resolve this.

#Table issue
Okay, we will check and will get back to you asap.

Regards.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

Please find our update as following.

#Feedback
**Status:** Done
**Screenshot:** http://prnt.sc/ervq6p
**Comment:** We have changed the icon as well as the fonts for upload field.

# Adapt the TCS tables to the actual V8 version.
**Status:** Done
**Screenshot:** http://prnt.sc/ervj3x

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Jignesh

ok, looks good. We originally thought that you will use the default CSS styling from TYPO3 and not with external CSS handling. but anyway: It works. Thanks for your help.

Regards,
Angelo
