### ISSUE TITLE
Please NO <table> HTML coding

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakerlist#3]
Please do not us a table layouting. Please change it with DIV layouting.

Concerning all this files:

- netc_bakerlist/netc_bakerlist/Resources/Private/Backend/Templates/Addresses/_List.html
- netc_bakerlist/netc_bakerlist/Resources/Private/Partials/Addresses/Properties.html
- netc_bakerlist/netc_bakerlist/Resources/Private/Templates/Addresses/List.html

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

NO <table> HTML coding
Status > Done
Screenshot > http://awesomescreenshot.com/09d5xnre65

Regards.
Thank You.
