### ISSUE TITLE
Add LLL files for frontend translations

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakerlist#4]
Please do add LLL files for frontend translations in templates.

Example:
<f:link.action action="new">New Addresses</f:link.action>

Replace it all with

<f:link.action action="new"><f:translate key="LLL:netcbakerlist/Ressources/Private/Language/locallang.xlfl:xxxx-new-addresses" /></f:link.action>

for example.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Add LLL files for frontend translations
Status > Done
Screenshot > http://awesomescreenshot.com/0115xnrp7b

Regards.
Thank You.
