### ISSUE TITLE
Uploading CSV file will not work

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakerlist#5]
If you choose the example file of the bakerlist.csv to upload nothing happens. There is only a message with "Failed to move uploaded files".

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Error in Upload files
Status > Done

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Upload works now, but there is NO BE view of the single entries in the SYS folder. Could you please add a BE view?

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

The BE View is already there, Please check following screenshots.

1. First Upload csv file in bakerlist folder
Screenshot - http://awesomescreenshot.com/0465xyy9a7
2. click on list->Bakerlist for view records in BE
Screenshot - http://awesomescreenshot.com/0005xyyq23

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hi
#1: OK.
#2: No. There is no backend! Could it be that it has some be_user restrictions? I do not see any items. See printscreens.
![bakerlist-be](https://cloud.githubusercontent.com/assets/17588253/16010082/dab2fd86-317f-11e6-93e6-5d0653f5e815.png)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Comments: Please set the "Default storage PID" from category "PLUGIN.TX_NETCBAKERLIST (4)" in constant Editor then you will see BE view.
Screenshot: http://prntscr.com/bgk0ig , http://prntscr.com/bgk0md

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Got the actual version downloaded and now there are TWO (2) different items im constants: One is BE and one if FE. If i insert the PID in the bough fields for BE and FE still the same. I do NOT see any items. See printscreens.
![bakerlist-ext](https://cloud.githubusercontent.com/assets/17588253/16115514/c18be85a-33c7-11e6-8b19-8392fd9e90b0.jpg)
![bakerlist](https://cloud.githubusercontent.com/assets/17588253/16115515/c18c1e56-33c7-11e6-8687-f7d9b19b9fb2.jpg)

**Comment by angeloprevitali** [comment]
![bakerlist-2](https://cloud.githubusercontent.com/assets/17588253/16115541/f01e0a36-33c7-11e6-8de3-313ef4bb8fc6.jpg)

**Comment by angeloprevitali** [comment]
![bakerlist-ext](https://cloud.githubusercontent.com/assets/17588253/16115546/fd98a46e-33c7-11e6-9037-59e5eaaa43b5.jpg)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status > Done
Comment > You have not set the Storage PID, that's why the output was not showing. Please check following screenshots.

Before Changed :
(1) http://awesomescreenshot.com/02a5yp16e9
(2) http://awesomescreenshot.com/0005yp1e31

After changed :
(1) http://awesomescreenshot.com/0df5yp0y67
(2) http://awesomescreenshot.com/0705yp1262

Output => http://awesomescreenshot.com/0d65yp4fee

Please review this and let us know your feedback for the same.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Got it. Works again.
