### ISSUE TITLE
How to call a search with active selected "glutenfreies Brot" 

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_bakerlist#7]
There must be a method to call up the search form with and without checked checkbox of "Glutenfreies Brot". Can you add a GET parameter for this?

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status > Done
Screenshot: http://prntscr.com/bg9rgt , http://prntscr.com/bgjm6p
Please use:
Realurl = http://192.168.0.121/html/netc/de/address/GlutenfreiesBrot/1/
without realurl = &tx_netcbakerlist_netcbakerlist[GlutenfreiesBrot]=1

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
By calling the url /?tx_netcbakerlist_netcbakerlist[GlutenfreiesBrot]=1 the checkbox is selected works, OK. 

But it should NOT display results yet after call up the page. Only after clicking the submit buttom. Can you fix this?

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status > Done
Screenshot-Without call up > http://prntscr.com/bj0bx6 
Screenshot-After call up the button > http://prntscr.com/bj0c4j
Video File: http://recordit.co/mmJCLaLW63

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Ok.
